### ISSUE TITLE
Open Action Items for open updates to tutorial document

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#34]
AI (Italo): Open Action Items for open updates to tutorial document

**Comment by ietf-mpls-yang** [comment]
Updated partially.

**Comment by ietf-mpls-yang** [comment]
Updated document to address Issue #22

**Comment by italobusi** [comment]
Need to update the tutorial to clarify how the reverse path is used with different types of bidirectional tunnels: see open issue #25

**Comment by italobusi** [comment]
Regarding open issue #22: still need to describe the use of the path-scope attribute

**Comment by italobusi** [comment]
Not sure we need to clarify the use of the disjointness attribute for primary path (see open issue #17): to be discussed

**Comment by italobusi** [comment]
Clarify the use of the preference attribute: see open issue #16

**Comment by ietf-mpls-yang** [comment]
Tutorial currently covers non-packet
Two options: add section in existing tutorial or new draft
Packet PM metrics.. FRR, etc.

**Comment by italobusi** [comment]
Need to discuss:
- [x] Segment Tunnel (issue #22)
- [x] Bidirectional Link in TE Topology
- [x] Bidirectional TE Tunnel (issue #25)
- [ ] Use of Disjointness attribute (issue #17)
- [ ] Use of Preference attribute (issue #16)

Need to write text:
- [x] Segment Tunnel (issue #22)
- [ ] Bidirectional Link in TE Topology: @sergiobelotti
- [ ] Bidirectional TE Tunnel: @italobusi look for the past notes
- [ ] Bidirectional TE Tunnel: @italobusi

**Comment by italobusi** [comment]
2019-05-17 Need to discuss also the use of Preference attribute (issue #16)

It has been closed today: https://github.com/tsaad-dev/te/issues/31#issuecomment-493487140

I am not sure what needs to be updated

**Comment by italobusi** [comment]
**2020-03-19 Italo/Sergio:**

All the open issues are tracked in github, better to close this one for cleaness
